example:
    property: I AM IN THE DEFAULT ACTUALIZADO
redis:
  server: redis
  port: 6379
signing:
  key: 3453345fsdfsf5345
spring:
    jpa:
      show-sql: true
      database: POSTGRESQL
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      url: jdbc:postgresql://database:5432/eagle_eye_local
      username: postgres
      password: password
      testWhileIdle: true
      validationQuery: SELECT 1
      platform: postgres
    database:
      driverClassName: org.postgresql.Driver
