example:
    property: I AM IN THE DEFAULT
redis:
  server: redis
  port: 6379
signing:
  key: 3453345fsdfsf5345
spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      dialect: PostgreSQLDialect
  datasource:
    platform: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/oreilly_database
    username: postgres
    password: postgres
